### ISSUE TITLE
Update installation documentation

### ISSUE THREAD

**Issue by mxposed** [openproblems-bio/website#207]
After recent updates I needed to install viash (and so java) and enable docker to be able to run quarto successfully. Anything else that I'm missing?

**Comment by rcannood** [comment]
I think that's about it. This is because quarto evaluates the code blocks in the documentation.

I'll look into whether it's possible to not eval the code blocks when doing a simple preview of the site.

**Comment by mxposed** [comment]
Good! I don't mind dependencies, and they don't seem to affect the runtime of preview task, I just didn't have them installed

**Comment by KaiWaldrant** [comment]
It should be possible with [render targets](https://quarto.org/docs/websites/#render-targets) and [Project Profiles](https://quarto.org/docs/projects/profiles.html).
I tried to create a `_quarto-no_docs.yaml` with following yaml:

```yaml
project:
  render: 
    - "*.qmd"
    - "!documentation/"
```
and executing following cmd did not result in the desirable result :):

`quarto preview --profile no_docs`

The cmd was still rendering the documentation.

**Comment by KaiWaldrant** [comment]
It also might be possible to add [profile content](https://quarto.org/docs/projects/profiles.html#profile-content) to the code blocks. I have not tried that so do not know if it works.

**Comment by rcannood** [comment]
I'd suggest creating a file `documentation/_blocks/_evaluate_code.qmd` with the following content:

    :::{.content-hidden when-profile="evaluate_code"}
    ```{r include=FALSE}
    knitr::opts_chunk$set(eval = FALSE)
    ```
    :::
    :::{.content-visible when-profile="evaluate_code"}
    ```{r include=FALSE}
    knitr::opts_chunk$set(eval = TRUE)
    ```
    :::

That way, the code chucks are still displayed but not evaluated, unless the profile `evaluate_code` is active. The CI should always use this profile, but for anyone making minor changes to the website, creating a preview will be much faster.

> Can we just put in some kind of try-catch in the rendering of code blocks?

I wouldn't use a try-catch, since the code being evaluated serves as a test to verify whether the documentation that we are providing also actually works.
