### ISSUE TITLE
Discuss `task_info.yaml` in docs

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/website#268]
There's currently no mention of this file at all. I don't know, for example, what are valid `roles`.

**Comment by KaiWaldrant** [comment]
see https://main--openproblems.netlify.app/documentation/create_task/define_task.html

**Comment by rcannood** [comment]
To elaborate a bit further on this:

> There's currently no mention of this file at all.

I agree with Kai here, it's already mentioned in the '[Define task](see https://main--openproblems.netlify.app/documentation/create_task/define_task.html)' documentation

> I don't know, for example, what are valid roles.

However, I also think this documentation could be expanded upon, because right now the documentation just shows you the format of a `task_info.yaml` file without describing each of the fields. Let's reopen this until we have more extensive descriptions in place.

**Comment by scottgigante-immunai** [comment]
Ah, I was looking in https://main--openproblems.netlify.app/documentation/create_task/design_api.html . Might be worth assuming that people won't read the docs end-to-end (e.g. if my task is already well-defined) and putting a mention of this file in the "design the API" section, even if it's just referencing the fact that it was created in the previous step.
