### ISSUE TITLE
A broken link to the NeurIPS 2021 dataset in the paper

### ISSUE THREAD

**Issue by VladimirShitov** [openproblems-bio/website#292]
The [paper](https://openreview.net/forum?id=gN35BGa1Rt) about NeurIPS 2021 competition, which is also referenced in the Best practices book (e.g., [this chapter](https://www.sc-best-practices.org/chromatin_accessibility/quality_control.html#id446)), contain a link to the dataset: https://openproblems.bio/benchmark_dataset . Unfortunately, this link is not working. 
<img width="434" alt="image" src="https://github.com/openproblems-bio/website/assets/35199218/57472f72-da77-46b6-ac53-58625c3bc93e">

Could you please fix this link and put the dataset back there? I think, it is important for community, and also would make the best practices book more reproducible. Maybe it also makes sense to write a test checking that the link works as expected

**Comment by rcannood** [comment]
Hey @VladimirShitov !

Thanks for reporting this issue!

I added a redirect to the list of redirects:

Contents of `_redirects`:

    /competitions /events
    /neurips /events/2021-09_neurips
    /neurips_2021 /events/2021-09_neurips
    /neurips_2022 /events/2022-08_neurips
    /neurips_2023 /events/2023-08_neurips
    /neurips_2021_docs/* /events/2021-09_neurips/documentation/:splat
    /competitions/neurips_2021 /events/2021-09_neurips
    /competitions/neurips_2022 /events/2022-08_neurips
    /competitions/neurips_2021_docs/* /events/2021-09_neurips/documentation/:splat
    /jamboree /events/2021-03_jamboree
    /benchmark_dataset /events/2021-09_neurips/documentation/data/dataset.html

These redirects were added to ensure that old URLs still point to the right content, but somehow this one was missed.

I don't plan on adding tests to the website repo, since it's mostly a collection of markdown files.

If you encounter any more issues, feel free to let us know :)
