### ISSUE TITLE
Website beautification

### ISSUE THREAD

**Issue by LuckyMD** [openproblems-bio/website#30]
Some notes from my side:
* metric names are too close together in the results table (also Paper Code and Year too close)
* Ordering results by rank would be good
* would be good to have a link to go back from dataset results to task
* we need task headings also where the task is explained: when you click on “label projection”, the next page should be titled “label projection”
* mentioned already several times, but thumbnails are not there atm

**Comment by dsm-72** [comment]
-     metric names are too close together in the results table (also Paper Code and Year too close) (feature not a bug, this is due to the sortable feature of the datatable library which overwrites manual padding)
-     Ordering results by rank would be good (was always that way?)
-     would be good to have a link to go back from dataset results to task (fixed elsewhere e.g. breadcrumbs)
-     we need task headings also where the task is explained: when you click on “label projection”, the next page should be titled “label projection” (was always that way?)
-     mentioned already several times, but thumbnails are not there atm (fixed elsewhere)
-     increase padding (done)
-     add gray 1px borders (done)
-     align numbers to the right, text to the left, headers central (No. Most of this is numbers and only the name needs to left align, paper center aligned)

**Comment by dsm-72** [comment]
see https://github.com/openproblems-bio/website/pull/88
