### ISSUE TITLE
Team page entries should be ordered alphabetical by surname

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/website#31]
Currently ordered alphabetical by first name, which is weird. Better still would be ordered randomly on every page load.

**Comment by rcannood** [comment]
I don't think its weird given that the names are displayed as "<First name> <Last name>". If it were displayed as "<Last name>, <First name>" then I agree it should be sorted by last name. 

Randomly ordering it might be possible by adding some javascript, though I don't think this is very high on the priority list. WDYT?

**Comment by scottgigante** [comment]
TBH I feel like ordered by first name is so unusual / unexpected that it implies some kind of hierarchy.

**Comment by rcannood** [comment]
Hmm.. On my phone, at least, all of my contacts are sorted alphabetically by first name (or as it appears on the screen).

Rather than change the formatting of the names of contributors or set up a function to randomly shuffle, how about I simply add a notice that contributors are ordered alphabetically.

**Comment by scottgigante** [comment]
That works for me!

**Comment by dburkhardt** [comment]
So I think if we edit the People partial, we can create a first_name, last_name variable for each person, and then just sort by last name, which is optimal. Random sorting is too much 😆 . That said, let's do this after all the other issues are closed

**Comment by rcannood** [comment]
Solved in #137
